name: My First Test Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Print a message
        run: echo "Hello Jay, GitHub Actions is working!"

      - name: Show files
        run: ls -la

      - name: Show current branch
        run: echo "Branch is $GITHUB_REF"